
PROVIDERS = {
        "FACEBOOK": ("FACEBOOK_APP_ID", "FACEBOOK_API_SECRET"),
        "TWITTER": ("TWITTER_CONSUMER_KEY", "TWITTER_CONSUMER_SECRET"),
        "LINKEDIN": ("LINKEDIN_CONSUMER_KEY", "LINKEDIN_CONSUMER_SECRET"),
}

class ProviderManager(object):
    pass
